//
// Created by totoro on 17/03/2022.
//

#ifndef CONCURRENT_TRIANGULATION_CONCURRENTTRIANGULATION_H
#define CONCURRENT_TRIANGULATION_CONCURRENTTRIANGULATION_H


class ConcurrentTriangulation {

};


#endif //CONCURRENT_TRIANGULATION_CONCURRENTTRIANGULATION_H
